[package]
name = "gui-vulkan"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
wgpu = "25.0"
winit = "0.30"
pollster = "0.4"
bytemuck = { version = "1.15", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
anyhow = "1.0"
